require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DietsController do

  # This should return the minimal set of attributes required to create a valid
  # Diet. As you add validations to Diet, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DietsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all diets as @diets" do
      diet = Diet.create! valid_attributes
      get :index, {}, valid_session
      assigns(:diets).should eq([diet])
    end
  end

  describe "GET show" do
    it "assigns the requested diet as @diet" do
      diet = Diet.create! valid_attributes
      get :show, {:id => diet.to_param}, valid_session
      assigns(:diet).should eq(diet)
    end
  end

  describe "GET new" do
    it "assigns a new diet as @diet" do
      get :new, {}, valid_session
      assigns(:diet).should be_a_new(Diet)
    end
  end

  describe "GET edit" do
    it "assigns the requested diet as @diet" do
      diet = Diet.create! valid_attributes
      get :edit, {:id => diet.to_param}, valid_session
      assigns(:diet).should eq(diet)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Diet" do
        expect {
          post :create, {:diet => valid_attributes}, valid_session
        }.to change(Diet, :count).by(1)
      end

      it "assigns a newly created diet as @diet" do
        post :create, {:diet => valid_attributes}, valid_session
        assigns(:diet).should be_a(Diet)
        assigns(:diet).should be_persisted
      end

      it "redirects to the created diet" do
        post :create, {:diet => valid_attributes}, valid_session
        response.should redirect_to(Diet.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved diet as @diet" do
        # Trigger the behavior that occurs when invalid params are submitted
        Diet.any_instance.stub(:save).and_return(false)
        post :create, {:diet => {}}, valid_session
        assigns(:diet).should be_a_new(Diet)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Diet.any_instance.stub(:save).and_return(false)
        post :create, {:diet => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested diet" do
        diet = Diet.create! valid_attributes
        # Assuming there are no other diets in the database, this
        # specifies that the Diet created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Diet.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => diet.to_param, :diet => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested diet as @diet" do
        diet = Diet.create! valid_attributes
        put :update, {:id => diet.to_param, :diet => valid_attributes}, valid_session
        assigns(:diet).should eq(diet)
      end

      it "redirects to the diet" do
        diet = Diet.create! valid_attributes
        put :update, {:id => diet.to_param, :diet => valid_attributes}, valid_session
        response.should redirect_to(diet)
      end
    end

    describe "with invalid params" do
      it "assigns the diet as @diet" do
        diet = Diet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Diet.any_instance.stub(:save).and_return(false)
        put :update, {:id => diet.to_param, :diet => {}}, valid_session
        assigns(:diet).should eq(diet)
      end

      it "re-renders the 'edit' template" do
        diet = Diet.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Diet.any_instance.stub(:save).and_return(false)
        put :update, {:id => diet.to_param, :diet => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested diet" do
      diet = Diet.create! valid_attributes
      expect {
        delete :destroy, {:id => diet.to_param}, valid_session
      }.to change(Diet, :count).by(-1)
    end

    it "redirects to the diets list" do
      diet = Diet.create! valid_attributes
      delete :destroy, {:id => diet.to_param}, valid_session
      response.should redirect_to(diets_url)
    end
  end

end
